# this is a whitelist of formulae that I want.
# clean up using this command
# brew bundle cleanup --force
# install or upgrade using
# brew bundle
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'ack'
brew 'bash-completion'
brew 'cmake'
brew 'coreutils'
brew 'cscope'
brew 'ctags'
brew 'dos2unix'
brew 'fzf'
brew 'go'
brew 'graphviz'
brew 'htop'
brew 'hugo'
brew 'imagemagick'
brew 'jq'
brew 'lua'
brew 'maven'
brew 'mono'
brew 'ngrep'
brew 'nmap'
brew 'node'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'rust'
brew 'sleepwatcher'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'terraform'
brew 'terragrunt'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'unrar'
brew 'wget', args: ['with-iri']
brew 'zsh'

tap 'homebrew/cask'
tap 'homebrew/cask-versions'

cask 'calibre'
cask 'dictunifier'
cask 'dropbox'
cask 'epic-games'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'iterm2'
cask 'macvim'
cask 'mplayerx'
cask 'osxfuse'
cask 'plex-media-player'
cask 'steam'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
