# this is a whitelist of formulae that I want.
# clean up using this command
# brew bundle cleanup --force
# install or upgrade using
# brew bundle
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'ack'
brew 'bash-completion'
brew 'coreutils'
brew 'dos2unix'
brew 'fzf'
brew 'graphviz'
brew 'htop'
brew 'imagemagick'
brew 'jq'
brew 'ngrep'
brew 'nmap'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'sleepwatcher'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'wget'
brew 'zsh'

tap 'homebrew/cask'
tap 'homebrew/cask-versions'

cask '1password'
cask 'aerial'
cask 'autodesk-fusion360'
cask 'blender'
cask 'calibre'
cask 'docker'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'google-earth-pro'
cask 'handbrake'
cask 'iterm2'
cask 'macvim'
cask 'openscad'
cask 'prusaslicer'
cask 'slic3r'
cask 'ultimaker-cura'
cask 'visual-studio-code'
cask 'vlc'
