# this is a whitelist of formulae that I want.
# clean up using this command
# brew bundle cleanup --force
# install or upgrade using
# brew bundle
tap 'homebrew/core'
tap 'homebrew/cask'

brew 'ack'
brew 'bash-completion'
brew 'container'
brew 'coreutils'
brew 'ctop'
brew 'dive'
brew 'dos2unix'
brew 'flyctl'
brew 'fzf'
brew 'git-lfs'
brew 'graphviz'
brew 'gnu-units'
brew 'htop'
brew 'imagemagick'
brew 'jq'
brew 'ngrep'
brew 'nmap'
brew 'node'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'sevenzip'
brew 'sleepwatcher'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'uv'
brew 'wget'
brew 'xmlstarlet'
brew 'xmlto'
brew 'yq'
brew 'zsh'

brew 'bat'
brew 'neovim'
brew 'pkl'
brew 'zellij'

brew 'tesseract'

cask '1password'
cask 'aerial'
cask 'anki'
cask 'blender'
cask 'calibre'
cask 'firefox'
cask 'google-chrome'
cask 'google-earth-pro'
cask 'handbrake-app'
cask 'iterm2'
cask 'keepingyouawake'
cask 'macvim-app'
cask 'obsidian'
cask 'openscad'
cask 'orcaslicer'
cask 'rectangle'
cask 'sanesidebuttons'
cask 'snapmaker-orca'
cask 'visual-studio-code'
cask 'vlc'

cask 'claude'
cask 'codex-app'
cask 'google-gemini'
cask 'lm-studio'
cask 'ollama-app'

cask 'airbuddy'
cask 'app-tamer'
cask 'bartender'
cask 'busycal'
cask 'cleanshot'
cask 'daisydisk'
cask 'keyboard-maestro'
# cask 'keycue' # commented out to keep keycue at 10.2. /opt/homebrew/Caskroom/keycue has been removed
cask 'swish'
cask 'textsniper'
cask 'unclutter'

