# .bashrc
function source_files() {
  local file

  for file in $DOTFILES/shell/*.sh; do
    source ${file}
  done

  for file in $DOTFILES/shell/bash/*.sh; do
    source ${file}
  done
}

if [[ -f ~/.shell.flags ]]; then
  source ~/.shell.flags
fi

source_files

if [[ -f ~/.bashrc.local ]]; then
  source ~/.bashrc.local
fi
