# .bashrc
function source_files() {
  local file

  for file in $DOTFILES/shell/*.sh; do
    source ${file}
  done

  for file in $DOTFILES/shell/bash/*.sh; do
    source ${file}
  done
}

source_files
