# .zshrc

function source_files() {
  local file

  for file in $DOTFILES/shell/*.sh
  do
    source ${file}
  done

  for file in $DOTFILES/shell/zsh/*.zsh
  do
    source ${file}
  done
}

source_files
